[package]
name = "user_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "user_lib"
crate-type = ["staticlib", "rlib"]
path = "src/lib.rs"
[dependencies]
xv_r_os = { path = "../" }
[profile.release]
strip = "symbols"